import React from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors } from '../theme/colors';

export function Screen({ title, children, onBack, onClose, right }: {title?:string; children:React.ReactNode; onBack?:()=>void; onClose?:()=>void; right?:React.ReactNode}) {
  return <View style={s.screen}><View style={s.nav}><Pressable onPress={onBack}><Text style={s.navIcon}>‹</Text></Pressable><Text style={s.title}>{title}</Text><View style={s.navRight}>{right}{onClose && <Pressable onPress={onClose}><Text style={s.close}>×</Text></Pressable>}</View></View><ScrollView contentContainerStyle={s.body}>{children}</ScrollView></View>;
}
export function Card({ children }: {children:React.ReactNode}) { return <View style={s.card}>{children}</View>; }
export function Row({ label, value, onPress, danger }: {label:string; value?:string; onPress?:()=>void; danger?:boolean}) { return <Pressable onPress={onPress} style={s.row}><Text style={[s.rowLabel, danger && {color:colors.darkRed}]}>{label}</Text><View style={s.rowValueWrap}>{value && <Text style={s.rowValue}>{value}</Text>}{onPress && <Text style={s.chev}>›</Text>}</View></Pressable>; }
export function Button({ title, onPress, variant='green' }: {title:string; onPress:()=>void; variant?:'green'|'red'|'light'}) { const bg = variant==='red'?colors.red:variant==='light'?colors.card:colors.green; return <Pressable onPress={onPress} style={[s.button,{backgroundColor:bg}]}><Text style={[s.buttonText, variant==='light' && {color:'#1677D2'}]}>{title}</Text></Pressable>; }
export function EmptyArt() { return <View style={s.emptyArt}><Text style={s.sparkle}>✦  ◦       ✳</Text><Text style={s.bubble}>?</Text><Text style={s.shadow}>▰</Text></View>; }
export function InputDialog({ visible, title, placeholder, value, setValue, onCancel, onConfirm }: {visible:boolean; title:string; placeholder:string; value:string; setValue:(v:string)=>void; onCancel:()=>void; onConfirm:()=>void}) { return <Modal transparent visible={visible} animationType="fade"><View style={s.overlay}><View style={s.dialog}><Text style={s.dialogTitle}>{title}</Text><TextInput style={s.input} placeholder={placeholder} value={value} onChangeText={setValue}/><View style={s.dialogActions}><Button title="Cancel" variant="red" onPress={onCancel}/><Button title="Confirm" onPress={onConfirm}/></View></View></View></Modal>; }
export function ActionSheet({ visible, title, actions, onCancel }: {visible:boolean; title?:string; actions:{label:string; onPress:()=>void}[]; onCancel:()=>void}) { return <Modal transparent visible={visible} animationType="slide"><View style={s.sheetOverlay}><View style={s.sheet}>{title && <Text style={s.sheetTitle}>{title}</Text>}{actions.map(a=><Pressable key={a.label} onPress={a.onPress} style={s.sheetItem}><Text style={s.sheetText}>{a.label}</Text></Pressable>)}</View><Pressable onPress={onCancel} style={s.cancelSheet}><Text style={s.sheetText}>Cancel</Text></Pressable></View></Modal>; }

const s = StyleSheet.create({ screen:{flex:1,backgroundColor:colors.bg,paddingTop:46}, nav:{height:56,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:24}, navIcon:{fontSize:42,color:'#111'}, close:{fontSize:36,color:'#111',marginLeft:14}, navRight:{minWidth:60,flexDirection:'row',justifyContent:'flex-end',alignItems:'center'}, title:{fontWeight:'700',fontSize:22,color:'#16181C'}, body:{padding:24,paddingBottom:40}, card:{backgroundColor:colors.card,borderRadius:12,borderWidth:1,borderColor:colors.line,marginBottom:26,overflow:'hidden',shadowColor:'#A8D8FF',shadowOpacity:.25,shadowRadius:12}, row:{minHeight:72,paddingHorizontal:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:colors.line}, rowLabel:{fontSize:18,color:'#555B63'}, rowValueWrap:{flexDirection:'row',alignItems:'center'}, rowValue:{fontSize:18,color:colors.muted,marginRight:12}, chev:{fontSize:44,color:'#202226'}, button:{borderRadius:12,minHeight:56,alignItems:'center',justifyContent:'center',paddingHorizontal:18,flex:1,marginHorizontal:6}, buttonText:{color:'#fff',fontWeight:'700',fontSize:18}, emptyArt:{alignItems:'center',marginVertical:42}, sparkle:{color:'#45D78E',fontSize:30}, bubble:{fontSize:76,color:'#A7F0BE',borderColor:'#A7F0BE',borderWidth:5,borderRadius:60,width:120,height:120,textAlign:'center'}, shadow:{color:'#A7F0BE',fontSize:72,marginTop:-44,opacity:.8}, overlay:{flex:1,backgroundColor:'rgba(0,0,0,.35)',justifyContent:'center',padding:24}, dialog:{backgroundColor:'#fff',borderRadius:12,padding:26,borderWidth:1,borderColor:'#76BFFF'}, dialogTitle:{textAlign:'center',fontSize:22,fontWeight:'700',marginBottom:38}, input:{borderBottomWidth:1,borderBottomColor:'#B8B8B8',fontSize:18,marginBottom:34,padding:8}, dialogActions:{flexDirection:'row'}, sheetOverlay:{flex:1,backgroundColor:'rgba(0,0,0,.35)',justifyContent:'flex-end',padding:10}, sheet:{backgroundColor:'#fff',borderRadius:12,overflow:'hidden'}, sheetTitle:{textAlign:'center',fontSize:16,color:'#888',padding:16,borderBottomWidth:1,borderBottomColor:'#ddd'}, sheetItem:{padding:22,alignItems:'center',borderBottomWidth:1,borderBottomColor:'#ddd'}, sheetText:{fontSize:24,color:'#1677D2'}, cancelSheet:{backgroundColor:'#fff',borderRadius:12,alignItems:'center',padding:22,marginTop:12,marginBottom:18} });
